version: "3.8"

services:
  pf-redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis_data:/data
    networks:
      pf:
        aliases:
          - "$REDIS_HOST"
    logging:
      driver: none
    restart: always
  pf-socket:
    image: meloncafe/pf-websocket:latest
    command: ["--tcpHost", "0.0.0.0"]
    hostname: socket
    networks:
      pf:
         aliases:
           - "$PATHFINDER_SOCKET_HOST"
    restart: always
  pf:
    hostname: "pathfinder"
    image: meloncafe/pathfinder:latest
    env_file:
    - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.pf.loadbalancer.server.port=80"
      - "traefik.http.routers.pf.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.pf.entrypoints=web"
    networks:
      - pf
    healthcheck:
      disable: true
    volumes:
      - ./config/pathfinder/config.ini:/var/www/html/pathfinder/app/templateConfig.ini
      - ./config/pathfinder/pathfinder.ini:/var/www/html/pathfinder/app/pathfinder.ini
      - ./config/pathfinder/plugin.ini:/var/www/html/pathfinder/app/plugin.ini
      - ./logs:/var/www/html/pathfinder/history/map
    depends_on:
      - pf-redis
      - pf-socket
    restart: always
    ports:
      - "40080:80"

volumes:
     data:
     redis_data:
networks:
    pf:
